import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions)
  if(!session){
    redirect("/")
  }
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-purple-500 w-48 p-4 flex flex-col items-center">
            <div className="">
                <Image src={session.user.image} alt="Logo" width={128} height={128} className="rounded-full border-4 border-yellow-400"/>
            </div>
          </aside>
        <div className="p-6 mx-auto max-w-4xl">
        {children}
        </div>
        </main>
      </body>
    </html>
  );
}
