import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import AppSidebar from "@/components/layout/AppSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/");
  }
  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-purple-700 w-48 p-4 flex flex-col items-center shadow-xl">
            <div className="">
              <Image
                src={session.user.image}
                alt="Logo"
                width={128}
                height={128}
                className="rounded-full border-4 border-yellow-400 shadow-xl"
              />
            </div>
           <AppSidebar/>
          </aside>
          <div className="grow">
            <div className="bg-slate-200 m-8 p-4 shadow-xl">
            {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
